name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  nuke-build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Run './build.cmd PublishGitHubRelease'
        run: ./build.cmd PublishGitHubRelease
        env:
          NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report
          path: '**/test-results.trx'
          reporter: dotnet-trx
