name: test

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
      - '**/LICENSE.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
      - '**/LICENSE.md'

jobs:
  nuke-build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Run './build.cmd Test'
        run: ./build.cmd Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report
          path: '**/test-results.trx'
          reporter: dotnet-trx
